services:
  backend:
    build: ./backend
    # monta el staticfiles en el host para poder leerlo desde nginx
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./db_data:/app/db_data


  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/staticfiles:/volumes/static:ro