# backend/Dockerfile

FROM python:3.10-slim

# No genere archivos .pyc y flush a stdout
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copiamos sólo requirements first para aprovechar cache
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install gunicorn

# Ahora copiamos el código
COPY . .

EXPOSE 8000

# Lanzamos Gunicorn
CMD ["gunicorn", "medical_system.wsgi:application", "--bind", "0.0.0.0:8000"]
