# backend/Dockerfile

FROM python:3.10-slim

# No genere archivos .pyc y flush a stdout
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copiamos sólo requirements first para aprovechar cache
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install gunicorn

RUN mkdir -p /app/staticfiles
# Ahora copiamos el código
COPY . .

EXPOSE 8000



# al final de backend/Dockerfile

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
